#!/bin/sh

set -e

if [ "$1" = "install" ] && [ -e /etc/X11/gdm/PostSession/Default.pre-fsck2.backup ] ; then
    rm /etc/X11/gdm/PostSession/AutoFsck
    rm /etc/X11/gdm/PostSession/Default.pre-fsck2.backup
    sed -e "/AutoFsck/d" -i /etc/X11/gdm/PostSession/Default
    chmod a+x /etc/X11/gdm/PostSession/Default
fi

exit 0
